version: '3.8'

services:
  proelectro-db:
    image: postgres:16-alpine
    container_name: proelectro-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pe_network

  proelectro-bot:
    build: .
    container_name: proelectro-bot
    restart: always
    depends_on:
      proelectro-db:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      GROUP_ID: ${GROUP_ID}
      BOSS_USERNAME: ${BOSS_USERNAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: proelectro-db
      DB_PORT: ${DB_PORT}
      WEB_PORT: ${WEB_PORT}
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      ADMIN_LOGIN: ${ADMIN_LOGIN}
      ADMIN_PASS: ${ADMIN_PASS} # <-- ИСПРАВЛЕНО ЗДЕСЬ
    # Мы убрали volumes, чтобы Docker брал файлы из образа
    ports:
      - "${WEB_PORT:-3000}:3000"
    networks:
      - pe_network

networks:
  pe_network:
    driver: bridge

volumes:
  pg_data: