version: '3.8'

services:
  proelectro-db:
    image: postgres:16-alpine
    container_name: proelectro-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pe_network

  proelectro-bot:
    build: .
    container_name: proelectro-bot
    restart: always
    depends_on:
      - proelectro-db
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:3000"
    networks:
      - pe_network

networks:
  pe_network:
    driver: bridge

volumes:
  pg_data: